{% set name = "archspec-base" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/archspec-{{ version }}.tar.gz
  sha256: 0974a8a95831d2d43cce906c5b79a35d5fd2bf9be478b0e3b7d83ccc51ac815e

build:
  number: 1
  noarch: python
  entry_points:
    - archspec = archspec.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - archspec
    - archspec.cpu
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: archspec-base

  - name: archspec
    requirements:
      run:
        - {{ pin_subpackage('archspec-base', exact=True) }}
        - click >=8,<9
    test:
      commands:
        - archspec --help

about:
  home: https://pypi.org/project/archspec/
  summary: A library to query system architecture
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  dev_url: https://github.com/archspec/archspec/
  doc_url: https://archspec.readthedocs.io/

extra:
  feedstock-name: archspec
  recipe-maintainers:
    - anthchirp
    - isuruf
