{% set name = "archspec" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/archspec-{{ version }}.tar.gz
  sha256: d07deb5b6e2ab3b74861e217523d02e69be8522f6e6565f4cc5d2062eb1a5d2c

build:
  number: 1
  noarch: python
  entry_points:
    - archspec = archspec.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - archspec
    - archspec.cpu
  commands:
    - pip check
    - archspec --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/archspec/
  summary: A library to query system architecture
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  dev_url: https://github.com/archspec/archspec/
  doc_url: https://archspec.readthedocs.io/

extra:
  recipe-maintainers:
    - anthchirp
    - isuruf
