context:
  name: archspec
  version: 0.2.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/archspec-${{ version }}.tar.gz
  sha256: d07deb5b6e2ab3b74861e217523d02e69be8522f6e6565f4cc5d2062eb1a5d2c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - archspec = archspec.cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - python >=3.6

tests:
  - python:
      imports:
        - archspec
        - archspec.cpu
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - archspec --help

about:
  summary: A library to query system architecture
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  homepage: https://pypi.org/project/archspec/
  repository: https://github.com/archspec/archspec/
  documentation: https://archspec.readthedocs.io/

extra:
  recipe-maintainers:
    - anthchirp
    - isuruf
